export interface Country {
    id: number,
    name: string
}

export const countries: Country[] = [
  { "id": 0, "name": "Afghanistan" },
  { "id": 1, "name": "Afrique du Sud" },
  { "id": 2, "name": "Albanie" },
  { "id": 3, "name": "Algérie" },
  { "id": 4, "name": "Allemagne" },
  { "id": 5, "name": "Andorre" },
  { "id": 6, "name": "Angola" },
  { "id": 7, "name": "Antigua-et-Barbuda" },
  { "id": 8, "name": "Arabie saoudite" },
  { "id": 9, "name": "Argentine" },
  { "id": 10, "name": "Arménie" },
  { "id": 11, "name": "Australie" },
  { "id": 12, "name": "Autriche" },
  { "id": 13, "name": "Azerbaïdjan" },
  { "id": 14, "name": "Bahamas" },
  { "id": 15, "name": "Bahreïn" },
  { "id": 16, "name": "Bangladesh" },
  { "id": 17, "name": "Barbade" },
  { "id": 18, "name": "Belgique" },
  { "id": 19, "name": "Belize" },
  { "id": 20, "name": "Bénin" },
  { "id": 21, "name": "Bhoutan" },
  { "id": 22, "name": "Biélorussie" },
  { "id": 23, "name": "Birmanie (Myanmar)" },
  { "id": 24, "name": "Bolivie" },
  { "id": 25, "name": "Bosnie-Herzégovine" },
  { "id": 26, "name": "Botswana" },
  { "id": 27, "name": "Brésil" },
  { "id": 28, "name": "Brunei" },
  { "id": 29, "name": "Bulgarie" },
  { "id": 30, "name": "Burkina Faso" },
  { "id": 31, "name": "Burundi" },
  { "id": 32, "name": "Cambodge" },
  { "id": 33, "name": "Cameroun" },
  { "id": 34, "name": "Canada" },
  { "id": 35, "name": "Cap-Vert" },
  { "id": 36, "name": "Centrafrique" },
  { "id": 37, "name": "Chili" },
  { "id": 38, "name": "Chine" },
  { "id": 39, "name": "Chypre" },
  { "id": 40, "name": "Chypre du Nord" },
  { "id": 41, "name": "Colombie" },
  { "id": 42, "name": "Comores" },
  { "id": 43, "name": "Congo (Brazzaville)" },
  { "id": 44, "name": "Congo (Kinshasa)" },
  { "id": 45, "name": "Corée du Nord" },
  { "id": 46, "name": "Corée du Sud" },
  { "id": 47, "name": "Costa Rica" },
  { "id": 48, "name": "Côte d'Ivoire" },
  { "id": 49, "name": "Croatie" },
  { "id": 50, "name": "Cuba" },
  { "id": 51, "name": "Danemark" },
  { "id": 52, "name": "Djibouti" },
  { "id": 53, "name": "Dominique" },
  { "id": 54, "name": "Égypte" },
  { "id": 55, "name": "Émirats arabes unis" },
  { "id": 56, "name": "Équateur" },
  { "id": 57, "name": "Érythrée" },
  { "id": 58, "name": "Espagne" },
  { "id": 59, "name": "Estonie" },
  { "id": 60, "name": "Eswatini" },
  { "id": 61, "name": "États-Unis" },
  { "id": 62, "name": "Éthiopie" },
  { "id": 63, "name": "Fidji" },
  { "id": 64, "name": "Finlande" },
  { "id": 65, "name": "France" },
  { "id": 66, "name": "Gabon" },
  { "id": 67, "name": "Gambie" },
  { "id": 68, "name": "Géorgie" },
  { "id": 69, "name": "Ghana" },
  { "id": 70, "name": "Grèce" },
  { "id": 71, "name": "Grenade" },
  { "id": 72, "name": "Guatemala" },
  { "id": 73, "name": "Guinée" },
  { "id": 74, "name": "Guinée équatoriale" },
  { "id": 75, "name": "Guinée-Bissau" },
  { "id": 76, "name": "Guyana" },
  { "id": 77, "name": "Haïti" },
  { "id": 78, "name": "Honduras" },
  { "id": 79, "name": "Hongrie" },
  { "id": 80, "name": "Îles Cook" },
  { "id": 81, "name": "Îles Marshall" },
  { "id": 82, "name": "Îles Salomon" },
  { "id": 83, "name": "Inde" },
  { "id": 84, "name": "Indonésie" },
  { "id": 85, "name": "Iran" },
  { "id": 86, "name": "Irak" },
  { "id": 87, "name": "Irlande" },
  { "id": 88, "name": "Islande" },
  { "id": 89, "name": "Israël" },
  { "id": 90, "name": "Italie" },
  { "id": 91, "name": "Jamaïque" },
  { "id": 92, "name": "Japon" },
  { "id": 93, "name": "Jordanie" },
  { "id": 94, "name": "Kazakhstan" },
  { "id": 95, "name": "Kenya" },
  { "id": 96, "name": "Kirghizistan" },
  { "id": 97, "name": "Kiribati" },
  { "id": 98, "name": "Kosovo" },
  { "id": 99, "name": "Koweït" },
  { "id": 100, "name": "Laos" },
  { "id": 101, "name": "Lesotho" },
  { "id": 102, "name": "Lettonie" },
  { "id": 103, "name": "Liban" },
  { "id": 104, "name": "Liberia" },
  { "id": 105, "name": "Libye" },
  { "id": 106, "name": "Liechtenstein" },
  { "id": 107, "name": "Lituanie" },
  { "id": 108, "name": "Luxembourg" },
  { "id": 109, "name": "Macédoine du Nord" },
  { "id": 110, "name": "Madagascar" },
  { "id": 111, "name": "Malaisie" },
  { "id": 112, "name": "Malawi" },
  { "id": 113, "name": "Maldives" },
  { "id": 114, "name": "Mali" },
  { "id": 115, "name": "Malte" },
  { "id": 116, "name": "Maroc" },
  { "id": 117, "name": "Maurice" },
  { "id": 118, "name": "Mauritanie" },
  { "id": 119, "name": "Mexique" },
  { "id": 120, "name": "Micronésie" },
  { "id": 121, "name": "Moldavie" },
  { "id": 122, "name": "Monaco" },
  { "id": 123, "name": "Mongolie" },
  { "id": 124, "name": "Monténégro" },
  { "id": 125, "name": "Mozambique" },
  { "id": 126, "name": "Namibie" },
  { "id": 127, "name": "Nauru" },
  { "id": 128, "name": "Népal" },
  { "id": 129, "name": "Nicaragua" },
  { "id": 130, "name": "Niger" },
  { "id": 131, "name": "Nigeria" },
  { "id": 132, "name": "Niue" },
  { "id": 133, "name": "Norvège" },
  { "id": 134, "name": "Nouvelle-Zélande" },
  { "id": 135, "name": "Oman" },
  { "id": 136, "name": "Ouganda" },
  { "id": 137, "name": "Ouzbékistan" },
  { "id": 138, "name": "Pakistan" },
  { "id": 139, "name": "Palaos" },
  { "id": 140, "name": "Palestine" },
  { "id": 141, "name": "Panama" },
  { "id": 142, "name": "Papouasie-Nouvelle-Guinée" },
  { "id": 143, "name": "Paraguay" },
  { "id": 144, "name": "Pays-Bas" },
  { "id": 145, "name": "Pérou" },
  { "id": 146, "name": "Philippines" },
  { "id": 147, "name": "Pologne" },
  { "id": 148, "name": "Portugal" },
  { "id": 149, "name": "Qatar" },
  { "id": 150, "name": "Roumanie" },
  { "id": 151, "name": "Royaume-Uni" },
  { "id": 152, "name": "Russie" },
  { "id": 153, "name": "Rwanda" },
  { "id": 154, "name": "Saint-Christophe-et-Niévès" },
  { "id": 155, "name": "Saint-Marin" },
  { "id": 156, "name": "Saint-Vincent-et-les-Grenadines" },
  { "id": 157, "name": "Sainte-Lucie" },
  { "id": 158, "name": "Samoa" },
  { "id": 159, "name": "Sao Tomé-et-Principe" },
  { "id": 160, "name": "Sénégal" },
  { "id": 161, "name": "Serbie" },
  { "id": 162, "name": "Seychelles" },
  { "id": 163, "name": "Sierra Leone" },
  { "id": 164, "name": "Singapour" },
  { "id": 165, "name": "Slovaquie" },
  { "id": 166, "name": "Slovénie" },
  { "id": 167, "name": "Somalie" },
  { "id": 168, "name": "Somaliland" },
  { "id": 169, "name": "Soudan" },
  { "id": 170, "name": "Soudan du Sud" },
  { "id": 171, "name": "Sri Lanka" },
  { "id": 172, "name": "Suède" },
  { "id": 173, "name": "Suisse" },
  { "id": 174, "name": "Suriname" },
  { "id": 175, "name": "Syrie" },
  { "id": 176, "name": "Tadjikistan" },
  { "id": 177, "name": "Tanzanie" },
  { "id": 178, "name": "Taïwan" },
  { "id": 179, "name": "Tchad" },
  { "id": 180, "name": "Tchéquie" },
  { "id": 181, "name": "Thaïlande" },
  { "id": 182, "name": "Timor oriental" },
  { "id": 183, "name": "Togo" },
  { "id": 184, "name": "Tonga" },
  { "id": 185, "name": "Trinité-et-Tobago" },
  { "id": 186, "name": "Tunisie" },
  { "id": 187, "name": "Turkménistan" },
  { "id": 188, "name": "Turquie" },
  { "id": 189, "name": "Tuvalu" },
  { "id": 190, "name": "Ukraine" },
  { "id": 191, "name": "Uruguay" },
  { "id": 192, "name": "Vanuatu" },
  { "id": 193, "name": "Vatican" },
  { "id": 194, "name": "Venezuela" },
  { "id": 195, "name": "Vietnam" },
  { "id": 196, "name": "Yémen" },
  { "id": 197, "name": "Zambie" },
  { "id": 198, "name": "Zimbabwe" },
  { "id": 199, "name": "Abkhazie" },
  { "id": 200, "name": "Haut-Karabagh" },
  { "id": 201, "name": "Ossétie du Sud" },
  { "id": 202, "name": "République arabe sahraouie démocratique" },
  { "id": 203, "name": "Transnistrie" },
  { "id": 204, "name": "Nouvelle-Calédonie" },
  { "id": 205, "name": "Porto Rico" },
  { "id": 206, "name": "Groenland" },
  { "id": 207, "name": "Guam" },
  { "id": 208, "name": "Îles Féroé" },
  { "id": 209, "name": "Sahara occidental" },
  { "id": 210, "name": "Tibet" }
];